version: "3.8"

services:
  backend:
    build: ./backend-repo
    ports:
      - "5001:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - app-network

  frontend:
    build: ./frontend-app
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - babyapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
